parameters:
#    tracker_billing.example.class: Tracker\BillingBundle\Example

services:
#    tracker_billing.example:
#        class: %tracker_billing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
