parameters:
#    tracker_ajax.example.class: Tracker\AjaxBundle\Example

services:
#    tracker_ajax.example:
#        class: %tracker_ajax.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
