Tracker\StationBundle\Entity\Station:
    type: entity
    table: station
    repositoryClass: Tracker\StationBundle\Entity\StationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mac:
            type: string
            length: '17'
            unique: true

    lifecycleCallbacks: ~

