Tracker\OuiBundle\Entity\Os:
    type: entity
    table: os
    repositoryClass: Tracker\OuiBundle\Entity\OsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: '50'
        color:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
