<?php

namespace Tracker\PlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxRepository extends EntityRepository
{
}
