<?php

namespace Tracker\PlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceConfigurationRepository extends EntityRepository
{
}
