Tracker\PlaceBundle\Entity\PlaceConfiguration:
    type: entity
    table: place_place_configuration
    repositoryClass: Tracker\PlaceBundle\Entity\PlaceConfigurationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: string
            length: 255
        created:
            type: datetime
        modified: 
            type: datetime
        
    manyToOne:
        place:
            targetEntity: \Tracker\PlaceBundle\Entity\Place
            inversedBy: configurations
        configuration:
            targetEntity: \Tracker\BoxBundle\Entity\Configuration
            
    lifecycleCallbacks:
        prePersist: [prePersist]
        preUpdate: [preUpdate]
