parameters:
#    rar_x_user.example.class: RarX\UserBundle\Example

services:
#    rar_x_user.example:
#        class: %rar_x_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
