parameters:
#    rar_x_api.example.class: Tracker\ApiBundle\Example

services:
#    rar_x_api.example:
#        class: %rar_x_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
