parameters:
#    tracker_box.example.class: Tracker\BoxBundle\Example

services:
#    tracker_box.example:
#        class: %tracker_box.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
