<?php

namespace Tracker\CaptureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CaptureCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaptureCacheRepository extends EntityRepository
{
}