<?php

namespace Tracker\CaptureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Capture3dRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Capture3dRepository extends EntityRepository
{
}
