Tracker\CaptureBundle\Entity\Capture:
    type: entity
    table: capture
    repositoryClass: Tracker\CaptureBundle\Entity\CaptureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCapture:
            type: datetime
            column: date_capture
        power:
            type: smallint
            nullable: true

    manyToOne:
        box: 
            targetEntity: \Tracker\PlaceBundle\Entity\Box
        station:
            targetEntity: \Tracker\StationBundle\Entity\Station

