parameters:
#    tracker_object.example.class: Tracker\ObjectBundle\Example

services:
#    tracker_object.example:
#        class: %tracker_object.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
