parameters:
#    tracker_oui.example.class: Tracker\OuiBundle\Example

services:
#    tracker_oui.example:
#        class: %tracker_oui.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
